### ISSUE TITLE
Is there a plublic api?

### ISSUE THREAD

**Issue by shadmansaleh** [ParsaAlizadeh/universal-parser-tool#20]
I was thinking of using this to parse tests .
I'd have loved if there was something like a get_test that would return the parsed test instead of writting them to disk .

```
get_tests(source, target_id/link)
-> [{'input': 'input_data', 'output': 'outputdata'}, .....]
```

Is this someting like this available here or only way to use it is as a cli tool ?

**Comment by ParsaAlizadeh** [comment]
No, it doesn't support this. If you don't need to parse tests from quera or usaco (which are the main reasons I use this tool), I recommend [oj-api](https://github.com/online-judge-tools/api-client)

**Comment by shadmansaleh** [comment]
Thanks . `oj-api` looks nice I'll try that .
